kind: ConfigMap
apiVersion: v1
metadata:
  name: monitoring-alertmanager-config
  namespace: app-monitoring
data:
  alertmanager.yml: |-
    global:
      resolve_timeout: 1m

    route:
      receiver: webhook
      group_by: ['alertname', 'cluster', 'service']

      group_wait: 5s
      group_interval: 10s
      repeat_interval: 4h

    inhibit_rules:
    - source_match:
        severity: 'error'
      target_match:
        severity: 'warning'
      # Apply inhibition if the alertname is the same.
      equal: ['alertname']

    receivers:
    - name: 'webhook'
      webhook_configs:
      - url: ${webhookUrl}
        send_resolved: false
        http_config: {}


