apiVersion: v1
kind: ServiceAccount
metadata:
  name: vks-state-metrics-sa
  namespace: app-monitoring
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vks-state-metrics-role
  namespace: app-monitoring
rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs: ["get"]
  - apiGroups: ["extensions"]
    resources:
      - deployments
    resourceNames: ["vks-state-metrics"]
    verbs: ["get", "update"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vks-state-metrics-cr
rules:
  - apiGroups: [""]
    resources:
      - configmaps
      - secrets
      - nodes
      - pods
      - services
      - resourcequotas
      - replicationcontrollers
      - limitranges
      - persistentvolumeclaims
      - persistentvolumes
      - namespaces
      - endpoints
    verbs: ["list", "watch"]
  - apiGroups: ["extensions"]
    resources:
      - daemonsets
      - deployments
      - replicasets
    verbs: ["list", "watch"]
  - apiGroups: ["apps"]
    resources:
      - statefulsets
    verbs: ["list", "watch"]
  - apiGroups: ["batch"]
    resources:
      - cronjobs
      - jobs
    verbs: ["list", "watch"]
  - apiGroups: ["autoscaling"]
    resources:
      - horizontalpodautoscalers
    verbs: ["list", "watch"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vks-state-metrics-rb
  namespace: app-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vks-state-metrics-role
subjects:
  - kind: ServiceAccount
    name: vks-state-metrics-sa
    namespace: app-monitoring
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vks-state-metrics-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vks-state-metrics-cr
subjects:
  - kind: ServiceAccount
    name: vks-state-metrics-sa
    namespace: app-monitoring
